### ISSUE TITLE
1주차 과제: 순차 자료구조 방식

### ISSUE THREAD

**Issue by cokeworld** [study-data-structure/study-data-structure#1]
# 목표
순차 자료구조 방식에 대해 학습하세요.
# 학습할 것
1. 순차 자료구조 방식의 의미와 특징
2. 선형 리스트의 구조와 연산
# 마감기한
2021년 3월 1일 월요일 오전 10시 까지.

**Comment by cokeworld** [comment]
1주차 과제 제출합니다.
https://cokeworld.tistory.com/38

**Comment by yunjinhyeong** [comment]
1주차 과제 제출입니다(세세하게 정리하여 앞에 제목앞 '5장'이라 적혀있는 전부입니다)
https://yju7257.tistory.com/29
