### ISSUE TITLE
3주차 과제: 스택, 큐

### ISSUE THREAD

**Issue by cokeworld** [study-data-structure/study-data-structure#3]
# 목표
스택, 큐에 대해 학습하세요.
# 학습할 것
1. 스택, 큐의 자료구조
2. 스택, 큐의 구현
3. 스택, 큐의 응용
# 마감기한
2021년 3월 15일 월요일 오전 10시 까지.

**Comment by yunjinhyeong** [comment]
https://yju7257.tistory.com/57
https://yju7257.tistory.com/58
7장과 8장 스택 큐에 대한 정리 입니다.

**Comment by cokeworld** [comment]
https://cokeworld.tistory.com/entry/%EC%8A%A4%ED%83%9D-%ED%81%90
과제 제출합니다.
